development:
    sessions:
        default:
            database: mongoid_dev
            username: root
            password: root
            hosts:
                - localhost:27017
production:
    sessions:
        default:
            database: mongoid_dev
            username: root
            password: root
            hosts:
                - localhost:27017
